sal_server/sal_server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sal_server/system/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'system'

urlpatterns = [
    # トップ
    path('', views.Top.as_view(), name='top'),
    # ログイン
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    # ユーザー作成
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    #予約系
    path('reservation_create/', views.Reservation_create.as_view(),name='reservation_create'),
    path('reservation_list/', views.Reservation_list.as_view(),name='reservation_list'),
    path('<int:pk>/delete/',views.Reservation_delete.as_view(), name='reservation_delete'),
    #施設検索系
    path('facility_list/', views.Facility_list.as_view(),name='facility_list'),
    #ランダム文字列受け取り
    path('random_string/', views.Random_string.as_view(),name='random_string'),
]

sal_server/system/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from stdimage.models import StdImageField 


class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    #ユーザー AbstractUserをコピペし編集
    """
    User
        ユーザーネーム : username
        姓 : last_name
        名 : first_name
        メール : email
        電話番号 : phone
    """

    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_(
            'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('姓'), max_length=30, blank=True)
    last_name = models.CharField(_('名'), max_length=150, blank=True)
    email = models.EmailField(_('メールアドレス'), blank=True)

    #追加 電話番号
    phone = models.CharField(_('電話番号'),max_length=12)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', ]

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    # 既存メソッドの変更
    def get_first_name(self):
        return self.first_name

    def get_last_name(self):
        return self.last_name

    #追加
    def get_phone(self):
        return self.phone

    


""" 予約 """
class Reservation(models.Model) : 
    """
        登録ユーザー : owner_id
        姓 : last_name
        名 : first_name
        団体名 : group
        施設 : facility
        利用目的 : use_kind
        人数_市内_男 : man_in
        人数_市内_女 : woman_in
        人数_市外_男 : man_out
        人数_市外_女 : woman_out
        送信用メールアドレス : email
        電話番号 : phone
        予約日付 : date_select
        利用時間 : time_for
        ランダム文字列 : rdm_str
    """
    owner_id = models.ForeignKey('User', on_delete=models.CASCADE)
    last_name = models.CharField("姓",max_length=10)
    first_name = models.CharField("名",max_length=10)
    group = models.CharField("団体名",max_length=30)
    facility = models.ForeignKey('Facility',verbose_name='施設',on_delete=models.CASCADE)
    use_kind = models.ForeignKey('UseKind',verbose_name='目的',on_delete=models.CASCADE)
    man_in = models.PositiveIntegerField("市内男性人数")
    man_out = models.PositiveIntegerField("市外男性人数")
    woman_in = models.PositiveIntegerField("市内女性人数")
    woman_out = models.PositiveIntegerField("市外女性人数")
    email = models.EmailField("メールアドレス",max_length = 200)
    phone = models.PositiveIntegerField("電話番号")
    date_select = models.DateTimeField("日付-時間")
    time_for = models.PositiveIntegerField("利用時間[時間]")
    rdm_str = models.CharField("ランダム文字列",max_length=640)
    """
    def get_people(self):
        return self.man_in + self.man_out + self.woman_in + self.woman_out
    """


""" 施設 """
class Facility(models.Model):
    """
        施設名 : facility
        エリア : area
        住所 : address
        画像id : picture
        部屋 : room
        詳細 : info

    """
    facility = models.CharField("施設名",max_length=30)
    #あとでなおす
    Area = models.ForeignKey('Area',on_delete=models.CASCADE)
    address = models.CharField("住所",max_length=300)
    room = models.ManyToManyField('Room')
    info = models.CharField("詳細",max_length=1000)
    picture = StdImageField("画像",upload_to='media/', blank=True, variations={
        'large': (600, 400),
        'thumbnail': (100, 100, True),
        'medium': (300, 200),
    })

    def __str__(self):
        return self.facility


""" 部屋 """
class Room(models.Model):
    """
        部屋名 : room
    """
    room = models.CharField("部屋名",max_length=30)

    def __str__(self):
        return self.room



""" 利用目的 """
class UseKind(models.Model):
    """
        利用目的 : use
    """
    use = models.CharField("利用目的",max_length=50)
    
    def __str__(self):
        return self.use



""" 検索用場所 """
class Area(models.Model):
    """
        場所 : area
    """
    area = models.CharField("エリア",max_length=30)

    def __str__(self):
        return self.area

sal_server/system/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm
)

from django.contrib.auth import get_user_model
User = get_user_model()

from .models import Reservation
import datetime

class LoginForm(AuthenticationForm):
    """ログインフォーム"""
    #Bootstrap用
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""
    class Meta:
        model = User
        if User.USERNAME_FIELD == 'email':
            fields = ('email',)
        else:
            fields = ('username', 'email')
    #Bootstarap用
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class ReservationForm(forms.ModelForm):
    """予約フォーム"""
    #date_select = forms.SplitDateTimeField(label='日付-時間')
    class Meta :
        model = Reservation
        fields = ['last_name','first_name','group','facility','use_kind','man_in','woman_in','man_out','woman_out','email','phone','date_select','time_for']
        widgets = {
            'last_name': forms.TextInput(attrs={'placeholder':'例：富浦'}),
            'first_name': forms.TextInput(attrs={'placeholder':'例：太郎'}),
            'group': forms.TextInput(attrs={'placeholder':'例：チーム○○'}),
            #'facility': forms.SelectMultiple(attrs={'placeholder':'選択してください'}),
            #'use_kind': forms.SelectMultiple(attrs={'placeholder':'選択してください'}),
            'man_in': forms.NumberInput(attrs={'placeholder':'数値を入力してください'}),
            'woman_in': forms.NumberInput(attrs={'placeholder':'数値を入力してください'}),
            'man_out': forms.NumberInput(attrs={'placeholder':'数値を入力してください'}),
            'woman_out': forms.NumberInput(attrs={'placeholder':'数値を入力してください'}),
            'email': forms.TextInput(attrs={'placeholder':'例：minamiboso@example.com'}),
            'phone': forms.NumberInput(attrs={'placeholder':'例：0001111222'}),
            #min追加する
            'date_select_0': forms.NumberInput(attrs={'placeholder':'例：2000-1-1'}),
            'time_for': forms.NumberInput(attrs={'placeholder':'例：1'})

        }
    #Bootstrap
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            

sal_server/system/templates/system/base.html
<!DOCTYPE>
<html lang="ja">

<head>

  {% load static %}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.0/fullcalendar.css"
    integrity="sha384-CSpejLAxvQjhYnaGctk31dTIAVVJ37ll9TXZ5+siSJ/ZYHLO6/Ae3wBxMkkeePta" crossorigin="anonymous">
  <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.0/fullcalendar.print.css"
    integrity="sha384-z97gwhg6eih9y0LEKeeKhp3kzktXuksd8JpECb6SWwru2UVRSD3KgsyEAwCXzTb1" crossorigin="anonymous"
    media='print'>
  <title>公共施設予約システム</title>

</head>

<body>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
    integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
    integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.1/moment.min.js"
    integrity="sha384-tMry5U11FUSp/GAwrcT5eBnH0jsu6qedzOXY3Y2YKBn0C5t6Y385r1Ek4CWDjbvC"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.0/fullcalendar.min.js"
    integrity="sha384-gyVAognIf5iCcX71QjZsjnNfQ074SU+gjJnQ16dCmmeSnoVglijgfmICPJlShL7c"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.0/locale/ja.js"
    integrity="sha384-3g00X8X6uNpt0mkFtoyT5J25ASNVc++QIeHgCWwdjDSF/Rf9txoUv+9bUgQ6tHdu"
    crossorigin="anonymous"></script>

  <!--datetimepicker -->
  <!--CSS-->
  <link href="{% static 'css/datepicker-widget.css' %}" type="text/css" media="all" rel="stylesheet">

  <!--JS-->
  <script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
  <script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
  <script type="text/javascript" src="{% static 'js/datepicker-widget.js' %}"></script>

  <!--balloon JS-->
  <script src="{% static 'js/jquery.balloon.js' %}"></script>

  {% block script %}{% endblock %}


  <!-- ナビバー -->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'system:top' %}">公共施設予約システム</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!--ナビゲーション-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        <li>
          <a class="nav-item nav-link " href="{% url 'system:top' %}">マイページ</a>
        </li>
        <li>
          <a class="nav-item nav-link " href="{% url 'system:facility_list' %}">施設検索</a>
        </li>
        <li>
          <a class="nav-item nav-link " href="{% url 'system:reservation_create' %}">予約</a>
        </li>
        <li>
          <a class="nav-item nav-link " href="{% url 'system:reservation_list' %}">予約リスト</a>
        </li>

      </ul>
      <ul class="navbar-nav ml-auto">
        <li>
          <a class="nav-item nav-link ml-auto" href="{% url 'system:logout' %}">ログアウト</a>
        </li>
      </ul>
      {% else %}
      <li class="nav-item">
        <a class="nav-item nav-link ml-auto" href="{% url 'system:login' %}">
          ようこそ、ゲスト！ログインはこちら
        </a>
      </li>
      {% endif %}
      </ul>
    </div>
  </nav>

  <!-- メインコンテント -->
  {% block content %}{% endblock %}





</body>

</html>

sal_server/system/templates/system/facility_list.html
{% extends "system/base.html" %}

{% block content %}
<div class="container mt-3">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-md-4 offset-md-4">
        <h1 class="my-3 text-center">施設検索</h1>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1">
          <div class="card mb-5">
            <div class="card-body">
              <form method="get" action="">
                <div class="row">
                  <div class="col-md-5 offset-md-2">
                    <div class="form-group mt-4 mb-4">
                      <select class="custom-select custom-select-lg" name="area">
                        <option selected>エリアを選択</option>
                        {% for a in areas %}
                        <option>{{ a }}</option>
                        {% endfor %}
                      </select>
                    </div>
                  </div>
                  <div class="col-md-3 mt-4">
                    <div class="form-group">
                      <button id="filter" class="btn btn-success btn-lg btn-block">施設検索</button>
                    </div>
                  </div>
                </div>
            </div>
            {% csrf_token %}
            </form>

          </div>
        </div>
      </div>
    </div>
    <div class="row">
      {% for f in facilities %}
      <div class="col-md-10 offset-md-1">
        <div class="card mb-4">
          <div class="card-header">
            <h3>{{ f.facility }}</h3>
          </div>
          <div class="card-body">
            <div class="row">

              <div class="col-md-4 mb-4">
                <img src="{{ f.picture.url }}" class="card-img mb-2">
              </div>

              <div class="col-md-8">
                <div class="row">

                  <div class="col-12">
                    <h2>施設説明</h2>
                  </div>

                  <div class="col-12" style="height:120px">
                    <p>・{{ f.info }}</p>
                  </div>
                  <div class="col-12">
                    <h5>住所</h5>・{{ f.address }}
                  </div>

                </div>

                <div class="row">
                  <div class="col-6">
                    <div class="form-group mb-4 mt-3">
                      <select class="custom-select" name="room">
                        <option selected>部屋一覧</option>
                        {% for r in f.room.all %}
                        <option>{{ r }}</option>
                        {% endfor %}

                      </select>
                    </div>
                  </div>

                  <div class="col-6 mb-4 mt-3 text-right">

                  <form action="{% url 'system:reservation_create' %}" method="GET">
                    <input type="hidden" name="facility" value="{{ f.facility }}">
                    <button type="submit" class="btn btn-success btn-block">予約</button>
                    {% csrf_token %}
                  </form>

                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>



{% endblock content %}

sal_server/system/templates/system/login.html
{% extends "system/base.html" %}
{% block content %}
<div class="container mt-3">
    <div class="row">
        <!-- 左側、ログインエリア -->
        <div class="container">
            <div class="row no-gutters">
                <div class="col-md-4 offset-md-4">
                    <h1 class="my-3 text-center">ログイン</h1>
                </div>
            </div>
            <div class="card col-md-4 offset-md-4 mt-2">
                <div class="card-body">

                    <form action="{% url 'system:login' %}" method="POST">
                        {{ form.non_field_errors }}
                        {% for field in form %}
                        {{ field }}
                        {{ field.errors }}
                        <hr>
                        {% endfor %}
                        <button type="submit" class="btn btn-success btn-lg btn-block">ログイン</button>
                        <input type="hidden" name="next" value="{{ next }}" />
                        {% csrf_token %}
                    </form>
                </div>
            </div><!-- 左側、ログインエリアおわり -->

            <!-- 右側、会員登録エリア -->
            <div class="card col-md-4 offset-md-4 mt-4">
                <div class="card-body">
                    <a href="{% url 'system:user_create' %}" class="btn btn-success btn-lg btn-block">会員登録</a>
                </div>
            </div><!-- 右側、会員登録エリアおわり -->
        </div>
    </div>
</div>
{% endblock %}

sal_server/system/templates/system/reservation_confirm_delete.html
<p>{{ object }} を削除していいですか?</p>
<form method="post">
  <button>削除する</button>
  {% csrf_token %}
</form>

sal_server/system/templates/system/reservation_form.html
{% extends "system/base.html" %}

{% block content %}

    <form method="post">
    {% csrf_token %}

    {{ form }}
    <button type="submit">save</button>
    </form>

{% endblock %}

sal_server/system/templates/system/reservation_list.html
{% extends "system/base.html" %}

{% block content %}

<div class="container">
  <div class="row no-gutters">
    <div class="col-md-4 offset-md-4">
      <h1 class="my-3 text-center">予約リスト</h1>
    </div>
  </div>
  <div class="row">
    {% for r in my_reservations %}
    <div class="col-md-6 offset-md-3">
      <div class="card mb-4">
        <div class="card-header text-center">
          <h2>{{ r.group }}</h2>
        </div>
        <div class="card-body">
          <div class="row">

            <div class="col-12">
              <h2>予約日時</h2>
            </div>

            <div class="col-12">
              <h5>・{{ r.date_select }}</h5>
            </div>
            <div class="col-12">
              <h2>場所</h2>
              <h5>・{{ r.facility }}</h5>
            </div>


            <div class="col-md-6 mt-3 offset-md-3">

              <form action="{% url 'system:reservation_delete' r.pk %}" method="POST">
                <button type="submit" class="btn btn-success btn-block">削除</button>
                {% csrf_token %}
              </form>


            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock content %}

sal_server/system/templates/system/top.html
{% extends "system/base.html" %}

{% block script %}
<script>
	$(document).ready(function () {
		$('#calendar').fullCalendar({
			timezone: "Asia/Tokyo",
			events: [
				{% for k, v in reservation_date.items %}      
				{
				start: "{{ k }}",
				end: "{{ k }}",
				title: "{{ v.f }}/{{ v.t }}~{{ v.e }}",
				color: '#5bc0de',

			},
			{% endfor %}
			]
		});
	{% for k, v in reservation_date.items %}
	$('td[data-date={{k}}]').balloon({
		html: true,
		contents: "{{ v.f }}/{{ v.t }}~{{ v.e }}"
	});
	{% endfor %}
	});
</script>

<style type="text/css">
	{% load static %}

	.jumbotron-extend {
		position: relative;
		height: 100vh;
		min-height: 300px;
		background: url("{% static 'system/tomiura.jpg' %}") no-repeat center center;
		background-size: cover;
	}
</style>

{% endblock %}

{% block content %}


<!-- PC用ページ -->
<div class="d-none d-lg-block">
	<!-- ジャンボトロン -->
	<div class="jumbotron jumbotron-extend mb-0 " style="height: 500px;">
		<div class="row">
			<div class="offset-7">
			<h1 class="text-white">施 設 利 用 をこれひとつで。</h1>
			</div>
		</div>
	</div>
	<!-- 利用方法 -->
	<div class="container">
		<div class="row no-gutters">
			<div class="col-md-4 offset-md-4">
				<h1 class="my-3 text-center">利用方法</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<a href="{% url 'system:facility_list' %}" class="card mb-4">
					{% load static %}
					<img class="card-img-top" src="{% static 'system/tomiura_ashiyu.jpg' %}" style="height: 300px;">
					<div class="card-body">
						<h3 class="card-title">施設検索</h3>
						<h6 class="card-text">施設の一覧から、エリアごとに検索することができます。</h6>
					</div>
				</a>
			</div>
			<div class="col-md-4">
				<a href="{% url 'system:reservation_create' %}" class="card mb-4">
					{% load static %}
					<img class="card-img-top" src="{% static 'system/reservation5.jpg' %}" style="height: 300px;">
					<div class="card-body">
						<h3 class="card-title">予約</h3>
						<h6 class="card-text">各種項目を入力して頂き、施設の予約を行うことができます。</h6>
					</div>
				</a>
			</div>
			<div class="col-md-4">
				<a href="{% url 'system:reservation_list' %}" class="card mb-4">
					{% load static %}
					<img class="card-img-top" src="{% static 'system/reservation3.jpg' %}" style="height: 300px;">
					<div class="card-body">
						<h3 class="card-title">予約リスト</h3>
						<h6 class="card-text">予約情報の確認・削除や、メールの再送を行うことができます。</h6>
					</div>
				</a>
			</div>
		</div>
		<div class="row no-gutters">
			<div class="col-md-4 offset-md-4">
				<h1 class="my-3 text-center">カレンダー</h1>
			</div>
		</div>
	</div>


</div>

<!-- スマートフォンページ -->
<div class="container mt-3 d-lg-none">

	<!-- ジャンボトロン -->
	<div class="jumbotron jumbotron-extend mb-0 " style="height: 300px;">
		<div class="container">
			<h2 class="text-white">施設利用を<br>これひとつで。</h2>


		</div>
	</div>
	<!-- 利用方法 -->
	<div class="container">
		<div class="row no-gutters">
			<div class="col-md-4 offset-md-4">
				<h1 class="my-3 text-center">利用方法</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="card mb-4">
					{% load static %}
					<a href="{% url 'system:facility_list' %}">
						<img class="card-img-top" src="{% static 'system/image001b.png' %}">
					</a>

					<div class="card-body">
						<h6 class="card-text">施設の一覧から、エリアごとに検索することができます。</h6>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="card mb-4">
					{% load static %}
					<a href="{% url 'system:reservation_create' %}">
						<img class="card-img-top" src="{% static 'system/image002a.png' %}">
					</a>
					<div class="card-body">
						<h6 class="card-text">各種項目を入力して頂き、施設の予約を行うことができます。</h6>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="card mb-4">
					{% load static %}
					<a href="{% url 'system:reservation_list' %}">
						<img class="card-img-top" src="{% static 'system/image003b.png' %}">
					</a>
					<div class="card-body">
						<h6 class="card-text">予約情報の確認、削除を行うことができます。</h6>
					</div>
				</div>
			</div>
		</div>
		<div class="row no-gutters">
			<div class="col-md-4 offset-md-4">
				<h1 class="my-3 text-center">カレンダー</h1>
			</div>
		</div>
	</div>
</div>

<!-- カレンダー -->
<div class="container mt-3">
	<style>
		#calendar {
			max-width: 900px;
			margin: 0 auto;
		}
	</style>
	<div id='calendar'></div>
</div>

{% endblock %}

sal_server/system/templates/system/user_create_complete.html
{% extends "system/base.html" %}
{% block content %}
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'system:login' %}">ログイン</a>
</p>
{% endblock %}

sal_server/system/templates/system/user_create_done.html
{% extends "system/base.html" %}
{% block content %}
<p>
    会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br>
    確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
</p>
{% endblock %}